[tox]
env_list =
    py311-django42-wagtail60
    py312-django52-wagtail70
    py313-django52-wagtail70
isolated_build = true

[testenv]
package = editable
extras = dev
commands = pytest {posargs}

[testenv:py311-django42-wagtail60]
basepython = python3.11
deps =
    Django>=4.2,<5.0
    wagtail>=6.0,<7.0

[testenv:py312-django52-wagtail70]
basepython = python3.12
deps =
    Django>=5.2,<6.0
    wagtail>=7.0,<8.0

[testenv:py313-django52-wagtail70]
basepython = python3.13
deps =
    Django>=5.2,<6.0
    wagtail>=7.0,<8.0
