# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_heimdallur", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationjob",
            name="remote_tasks",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
