# Generated by Django 5.2.15 on 2026-06-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_heimdallur', '0002_translationjob_remote_tasks'),
        # Match 0001's low/squashed wagtailcore dependency so the app installs on
        # the full supported Wagtail range (6.0+) rather than pinning to a
        # version-specific wagtailcore migration.
        ('wagtailcore', '0001_squashed_0016_change_page_url_path_to_text_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationjob',
            name='replaced_edits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TranslationSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_key', models.CharField(max_length=255)),
                ('source_hash', models.CharField(max_length=64)),
                ('translation_hash', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heimdallur_translation_segments', to='wagtailcore.page')),
            ],
            options={
                'indexes': [models.Index(fields=['target_page', 'segment_key'], name='wagtail_hei_target__46c948_idx')],
                'constraints': [models.UniqueConstraint(fields=('target_page', 'segment_key'), name='heimdallur_unique_segment_per_target')],
            },
        ),
    ]
